#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

trimmomatic_dir: ''
trimmomatic_exec: ''
adapters: ''


# --- filter_host_reads --- #

use_host_filter:         False
host_reference_database: ''