#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_adapters --- #

trimmomatic_dir: /home/lam4003/bin/anaconda3/share/trimmomatic-0.39-2


# --- filter_host_reads --- #

host_reference_database: /athena/masonlab/scratch/databases/metagenomics/HG37_Index/hg37dec_v0.1
