#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

trimmomatic_dir: /home/btierney/bin/Trimmomatic-0.39/
trimmomatic_exec: /home/btierney/bin/Trimmomatic-0.39/
adapters: /home/btierney/bin/Trimmomatic-0.39/

# --- filter_host_reads --- #

use_host_filter:         True
host_reference_database: /home/btierney/bin/databases/GRCh38_noalt_as/GRCh38_noalt_as
